FROM golang:1.11-stretch
RUN apt-get update && apt-get install -y vim tree lsof
ENV GOPATH=/home/bitum/go
ENV PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$GOPATH/bin
ENV BITUMSRC_PATH=$GOPATH/src/github.com/bitum-project/bitumdata/
ENV GO111MODULE=on
RUN useradd bitum -m -s /bin/bash && chown -R bitum:bitum /home/bitum
WORKDIR $BITUMSRC_PATH
RUN chown -R bitum:bitum $GOPATH
USER bitum
# since we might be rebulding often we need to cache this module layer
# otherwise docker will detect changes everytime and re-download everything again
COPY go.* $BITUMSRC_PATH
RUN go mod download
COPY . $BITUMSRC_PATH
RUN go build
CMD /bin/bash
ENTRYPOINT ./bitumdata
# Note: when building the --squash flag is an experimental feature as of Docker 18.06
# docker build --squash -t bitum-project/bitumdata .
# running
# docker run -ti --rm bitum-project/bitumdata
# or if attaching source volume and developing interactively
# docker run -ti --entrypoint=/bin/bash -v ${PWD}:${PWD}:/home/bitum/go/src/github.com/bitum-project/bitumdata --rm bitum-project/bitumdata