FROM golang:1.10-alpine3.8
RUN apk update && apk add vim tree lsof bash git gcc musl-dev
ENV GOPATH=/home/bitum/go
ENV PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$GOPATH/bin
ENV BITUMSRC_PATH=$GOPATH/src/github.com/bitum-project/bitumdata/
RUN adduser -s /bin/bash -D -h /home/bitum bitum && chown -R bitum:bitum /home/bitum
WORKDIR $BITUMSRC_PATH
# since we might be rebulding often we need to cache this module layer
# otherwise docker will detect changes everytime and re-download everything again
RUN go get -u -v github.com/golang/dep/cmd/dep
COPY Gopkg* $BITUMSRC_PATH
# we perform a vendor ensure here to speed up future layers
RUN touch main.go && dep ensure -vendor-only
COPY . $BITUMSRC_PATH
RUN chown -R bitum:bitum $GOPATH
USER bitum
RUN dep ensure && dep ensure --vendor-only && go build
CMD /bin/bash

ENTRYPOINT ./bitumdata
# Note: when building the --squash flag is an experimental feature as of Docker 18.06
# docker build --squash -t bitum-project/bitumdata .
# running
# docker run -ti --rm bitum-project/bitumdata
# or if attaching source volume and developing interactively
#  docker run -ti --entrypoint=/bin/bash -v ${PWD}:/home/bitum/go/src/github.com/bitum-project/bitumdata --rm bitum-project/bitumdata